### ISSUE TITLE
Forcing ps2_netemu hangs fullBC console

### ISSUE THREAD

**Issue by Haker120** [Zarh/ManaGunZ#10]
When I try to force ps2_netemu mounting through managunz, it mounts ps2 CD/DVD correctly but when I try to run mounted game, my CECH-A hangs and resets itself, however, forcing ps2_netemu through rebug toolbox work well. Now I try the newest version and it helped a bit but no sound in-game, those issues don't appear when forcing ps2_netemu through toolbox.

**Comment by Zarh** [comment]
Thank you for your feedback.

Just to be sure when you enable it with the toolbox, do you have the following message : "PS2 Emulator is set to use Software Emulation, exiting to XMB" ?

I'll investigate...

**Comment by Haker120** [comment]
Yes, that's a message in REBUG toolbox and ps3 resets itself and option ps2_netemu is on untill next console's reset.

**Comment by Zarh** [comment]
ok, and when u enable it on ManaGunZ, do you have the notification "Done !" ? 
(sry I can't test this function as I don't have a BC system)

**Comment by Haker120** [comment]
No, I didn't notice message 'done' only goes back to xmb.

**Comment by Zarh** [comment]
It looks like you didn't use the function to force ps2_netemu on ManaGunZ.
Go to game properties and enable ps2_netemu, you'll have the message "Done", then mount the backup and launch it in the xmb.

**Comment by Haker120** [comment]
Thanks for answer, that works today. :D
