### ISSUE TITLE
Separate HDD Unlock into 2 toggles?

### ISSUE THREAD

**Issue by rhynec** [Zarh/ManaGunZ#105]
By default, 3141card's code both decreases the amount of reserved space in the partition and sets a flag to improve file fragmentation in exchange for slower HDD writing speeds (in general). Perhaps it would be best to have these two functions separated from one another, so that one can unlock space in the HDD without sacrificing HDD speed, or leave the reserved space alone while improving overall fragmentation. What do you think @Zarh?

Edit: Btw, I uploaded what I think is a valid backup of the source code for your GamePadTest utility [here](https://github.com/rhynec/GamePadTest). Maybe you'd like to have the repo tied to your account? I can also take it down, if you wish.

**Comment by Zarh** [comment]
I kept exactly what 3141card did because he knows so much more than me, he actually learnt me some stuff... So, I assumed he did the best/simplest solution. Also, I have no idea what is this optimisation...

About gamepadtest, I'll try to upload and update it, I had few idea to improve it.... btw, it'll be probably included in Settings of managunz one day

**Comment by rhynec** [comment]
> Also, I have no idea what is this optimisation...

This is what eisteinx2 (the one who originally discovered this is possible on the PS3) said about it on psx-place:

> UFS2 supports two write optimization modes: time and space. Time optimization is the default--and is used by the PS3--and allows for faster writes at the expense of potentially higher fragmentation (though generally only as the drive reaches capacity). Since we're allowing ourselves to fill almost the entire drive, these instructions also change the optimization mode to space. That means that the filesystem will spend more time during writes to ensure the files are less fragmented, insinuating that it will shuffle blocks around to make contiguous space.

[This](https://github.com/rhynec/psl1ghtv2_ports/blob/f0e438512bdc86bdc7b8274ec3bf9d3ec4030ce1/unlock_hdd/source/main.c#L92) is the variable which controls the optimization trade-off in the filesystem (0 optimized for speed, 1 optimized for fragmentation). Since you're removing the reserved space which prevents fragmentation, it is ideal to set this flag in order to reduce it as much as possible when the drive is full.

But I agree, for simplicity's sake it'd be best to leave 3141card's defaults untouched.
