### ISSUE TITLE
How to build managunz

### ISSUE THREAD

**Issue by zssllayers19460** [Zarh/ManaGunZ#109]
I have tried to build it but i get an error about psl1ght base_rules when ive got the ps3toolchain, psl1ght, ps3libraries installed aswell as official sdk 4.75 i dont seem to find any info about the error so i was wonder if theres some packages i need to build it that i dont have installed 

Also im on windows with cygwin & mingw

**Comment by rhynec** [comment]
What exactly is the error you are getting?

In theory, you should be able to build this project with vanilla PSDK3v2. Also make sure your PSL1GHT installation is using gcc-4, as gcc-7 will not work with older project like MGZ.

I don't use Windows, but I do have Linux ps3toolchain binaries which are able to build MGZ properly [here](https://github.com/PS3SDK-Misc/SDK-Build/releases/tag/2022.02.18_200329).

FYI, cloning this repo and committing your changes to GitHub should trigger an automated workflow build which uses my PSL1GHT binaries to build MGZ. The final pkg should be published under releases (though, there's sometimes problems with this step; you can also find the pre-built pkgs under your workflow run as an "assets" tarball.

**Comment by Zarh** [comment]
I'm using this : https://github.com/Estwald/PSDK3v2

**Comment by RobbedColek** [comment]
A different SDK is being used than PSDK3v2 for compiling PS2_EMU payloads (`PS3DEV2:=$(PS3SDK)/ps3dev2`) - could you give some insight as to which one is it?

EDIT:
I've managed to build PS2_EMU payloads using PS3DEV2 that I found in Cobra 7.3 repository.
