### ISSUE TITLE
After Hen 3.1.0 Update is Enabled ManagunZ Start-up, Loading Screen Freeze

### ISSUE THREAD

**Issue by Bonethugs1980** [Zarh/ManaGunZ#111]
Please see details below, this is after the recent update of Hen version mentioned in title (all current working official releases from scene):

Once Hen 3.1.0 and latest  3.1.1 (auto update) is enabled, going into ManaGunZ 1.40 show the following visual and text on black screen (the startup-loading screen before it goes into ManaGunZ xmb):

Status bar with ManaGunz Icon just above status text below

'Loading lvl1 in memory...
Searching lvl2 offsets...
Loading lvl2 in memory...
New firmware ! Please wait while MGZ search for the new offsets...
read_fw_unk
Initialization'

At bottom of same loading screen shows usual:

'---Hide logs [Square Button] ===========boost! Cancel Button'

PS3 hard drive light flashes just as this loads then stops, due to freezing of above screen and does not go further.  Has to be manually shut off e.g. unplugged etc (then usual system file check and so on).

Notes: Tried holding down 'Square' button to speed boost, not sure if this feature works as intended, but the progress bar goes about 1/4 of the way (ps3 pad starts rumbling) then stops, due to freeze.

Assuming this is more to do with latest 4.89 HFW, regardless of the HEN Enabler.

**Comment by Zarh** [comment]
try this one please : https://github.com/Zarh/ManaGunZ/releases/tag/nightly

**Comment by Bonethugs1980** [comment]
Thanks a lot Zarh, that worked!  ManaGunZ loads as normal, tested one PS3 game loading from it as well - no further issues.

Thanks again, closing this with above comment :)
