### ISSUE TITLE
Failed to upload IRD

### ISSUE THREAD

**Issue by EdnessP** [Zarh/ManaGunZ#112]
When dumping all of my games, once encrypted to submit to Redump.org and once decrypted to get the IRD, if the IRD isn't in the database, I always get the error "failed to upload IRD."  If the IRD matches an entry in the database, it says "everything went well!" although I don't think it actually submitted anything, because my name never appeared on there.  My PS3 is connected to the internet, I can connect to PSN and play online games, so it's likely not an issue on that side.

I am using ManaGunZ 1.41, although not the latest version because of issue #95.
![image](https://user-images.githubusercontent.com/55930127/169667476-7403141e-e22e-4aa5-904e-f88a7485fb14.png)

As a test to see what the error would be if my PS3 was actually disconnected from the internet, it was a [completely different message](https://user-images.githubusercontent.com/55930127/169667545-f6fa85dd-20ff-4d60-88ec-88d83d8aae52.png), which also reaffirmed to me that it's most likely not an internet-related issue on my side.

Is there any other way I can send my IRDs to either one of you, or whoever else may be maintaining the ps3ird.free.fr database?  I have all of my IRDs saved, and I wouldn't want to have to re-dump them again, because especially really large games that take almost the entire 50GB of the space on a bluray disc took an insane amount of time to hash/build the IRD.

**Comment by EdnessP** [comment]
I did enable logs, but it doesn't seem to show anything of that sort.  It just fails almost instantly if the IRD isn't in the database.  And as before, if it already in in the DB, it'll say everything went well, without actually doing anything.  [Here is a recording of all that's shown when the IRD is finished building](https://youtu.be/DHLFYH9xl4U).

[And here's all my IRDs dumped so far](https://cdn.discordapp.com/attachments/451101723789099008/977883171892899850/PS3ISO.7z).

**Comment by Zarh** [comment]
I'll see if I can fix the issue with uploads, you're probably not the only one having it.

Thanks for the files, I uploaded them directly to the server : http://ps3ird.free.fr/

**Comment by Zarh** [comment]
You wrote : 
I am using ManaGunZ 1.41, although not the latest version because of issue https://github.com/Zarh/ManaGunZ/issues/95.


But this issue seems to be on v1.41, so maybe you are using managunz 1.40 ?
If yes then it's normal you failed the upload because the.server doesn't accept them anymore. Few ird built 1.40 are corrupted nothing important .So, I was checking 1 by 1 every ird before the v1.41, it took me lot of time that's why now it doesn't accept them anymore.

**Comment by EdnessP** [comment]
The name in the XMB says v1.41, and according to the changelog, the reimplementation of GetKey for Redump.org submissions was also added in 1.41, which is available for me in this version too.
![image](https://user-images.githubusercontent.com/55930127/170668597-53e19acb-e639-4847-a647-883be38a1912.png)

**Comment by EdnessP** [comment]
Just tried on the latest v1.42 nightly 66f1d0e and it seems to have successfully uploaded the IRD.
