### ISSUE TITLE
Issue with dumping a decrypted image

### ISSUE THREAD

**Issue by Bigmanjapan** [Zarh/ManaGunZ#115]
http://forum.redump.org/topic/44548/fixed-ps3-x1/

As stated by user7 in this thread:

> When dumping in console "decrypted dump" fails but "encrypted dump" doesnt. As in when managunz tries to decrypt the disc it wont

The disc in question is `Guitar Hero - Warriors of Rock (Australia) (Demo) BLUD-80021`.

Interesting thing about this disc is that since it stores its content in PKG files (which are excluded from disc encryption routine along with SFO files, SFB files and PUP etc files), the only file that ends up being actually encrypted is `PS3_GAME\LICDIR\LIC.DAT`. Maybe the encrypted portion being so small has something to do with ManaGunZ failing to make a decrypted image?

I can manually decrypt the encrypted image via PS3Dec with no issues.

![image](https://user-images.githubusercontent.com/31383389/171989448-b537b225-a162-4a89-8bc4-83bbdbc07b82.png)

**Comment by Zarh** [comment]
I have kind of copied/pasted the source code of ps3dec in ManaGunZ, so, it should be able to decrypt it.

I have no idea what's happening because there 32 sectors encrypted and ManaGunZ decrypt 1 sector at a time. So, I don't think it's the issue. It would be helpfull to get the error message (or/and the encrypted dump).

**Comment by Bigmanjapan** [comment]
You can get the encrypted image here: https://archive.org/details/redump-id-93812

Can't provide error message.

**Comment by Zarh** [comment]
I just made and tested with a similirar function in managunz; instead of reading from disc it reads sectors from iso and it works. I think he's in HEN, that's why he can't decrypt it.

I'm closing this issue, as I can't get any error message I'm stuck.
