### ISSUE TITLE
Dumping decrypted images in HEN environment. 

### ISSUE THREAD

**Issue by Bigmanjapan** [Zarh/ManaGunZ#117]
Recently a user Leniek reported that he was able to dump a decrypted image via MultiMAN on his CECH-3004B console modded with HFW 4.89.1 / HEN 3.1.1. At the same time, ``Dump decrypted Blu-Ray disc`` option is outright absent in ManaGunZ.

If MultiMAN is capable of creating decrypted images under HEN environment, shouldn't ManaGunZ be able to do it too? And if it's possible to create decrypted images, should it also be possible to retrieve full GetKey infromation about a disc?

**Comment by KamilLenica** [comment]
I am this user, feel free to ask for more details

**Comment by Zarh** [comment]
I think I already implemented it, it's the option I called "Build decrypted ISO"

**Comment by Zarh** [comment]
@KamilLenica 

Just to be sure, how did you get your ISO ? Is it : Triangle > create iso ?

**Comment by KamilLenica** [comment]
@Zahr

I've created encrypted iso using ManaGunZ, and JB format (folder) with multiman

**Comment by Zarh** [comment]
FYI, to get JB dump on MGZ you can use "Copy" option.

I closing this issue.
