### ISSUE TITLE
Allow downloading IRDs with only meta+file signature

### ISSUE THREAD

**Issue by rhynec** [Zarh/ManaGunZ#129]
I'm currently building a CLI tool for rebuilding folder rips into "proper" ISOs, and I would like to add an option to automatically retrieve IRDs based on the contents of the rip. However, building a link for an ISO in your database also requires the keys and extra signature, which are impossible to obtain from a folder rip. 

First, would it be ok to use your database for a project like that. If so, would it be possible to add a way to retrieve IRDs only using the meta and file signatures?

**Comment by Zarh** [comment]
yes, you can
do a HTTP GET
-If the file doesn't exist it return 404
-if it exists you'll get a list a filenames starting with it, here an example :
http://ps3ird.free.fr/script.php?ird=CF62ADEC
You can get a look at the function in ird_tools, here the function I use to get the crc I named "meta_sig"  : https://github.com/Zarh/ird_tools/blob/main/main.c#L566

I also wrote a mémo inside the main.c of managunz to explain how I calculate MGZ_SIG  just in case I forgot in the futur why I didn't something like that :) ; search "The goal of IRD_meta_sig"

**Comment by rhynec** [comment]
Thanks Zar, I didn't know you already implemented something like that on your end. I've been using your documentation on the IRD format from ird_tools, so you've already been a huge help. I'll be sure to credit you once I publish the project!
