### ISSUE TITLE
not really an issue

### ISSUE THREAD

**Issue by zefie** [Zarh/ManaGunZ#13]
I know this is annoying, I would comment on main.c but its huge and laggy on github :D

I was wondering if we could talk about your ISO reading functions in main.c, specifically get_FileOffset. I am trying to port the ird/iso functionality of ManaGunZ to a cli iso mass-validator. I've made progress but when it comes to it reading PARAM.SFO, it cannot find it and the root cause is get_FileOffset.

I was wondering if I was running into an endian issue, since PC is LE and PS3 is BE. Is there anything endian specific in that function?

If you are willing to help, we can talk here, or zefie#0573 on Discord. Thanks!

**Comment by zefie** [comment]
btw, on the topic of IRD, but less so of ManaGunZ, [here](http://www.psx-place.com/threads/how-to-create-ird.3284/#post-26008) you mention creating an IRD with an exe. 

Naturally we don't want this to be too public for the fear of a flood of fake IRDs, but are you implying there is a way to create an IRD without a 3k3y?

I have tried everything (Mana, multiman, right now I have iSCSI access to the PS3 BD-R via PS3 Linux). I just want to create some IRDs for some missing games.

I've also been trying to get in touch with jonnysp as I created a [firmware database](https://archive.midnightchanne.net/SonyPS/PS3/) that, if he updated PS3-ISO-Creator, could fix the "Download PS3UPDAT.PUP?" feature that is currently broken.

**Comment by Zarh** [comment]
jonnysp didn't create the iso dumper, it's a software from the 3k3y team which is closed source. And the team doesn't exist anymore.

**Comment by zefie** [comment]
I'm close to replicating an encrypted 3k3y iso header, just need to modify
getkey to get a proper key. I have discs with ird to test with.

I know he didn't create the dumper but I want to speak to him about my
project. Thanks for the response. 😀

**Comment by zefie** [comment]
here is the code to make a header (disc.key), if you can dump in direct (encrypted) mode, and add this header to the iso at 3952 bytes (overwrite), then you could make a 3k3y iso that we can make ird from.

https://github.com/zefie/getkey_gameos_zefie

**Comment by kiganazil** [comment]
Hello, I have a PS3 Super Slim 4004 with HFW 4.88 and HEN 3.0.3

I am using ManaGunZ 1.40 to dump encrypted disc iso but I cant create IRD using 3k3y ISO tools. Can something done about this to make 3k3y ISO tools to recognize the encryped iso and generate IRD? I ask this because I have a copy of BCES01888-[Beyond Two Souls(TM)] that has a newer version (maybe different pressing) than on the IRD that I found (I gave app version and game version 2.0)

Unfortunately, I think I can't dump decrypted disc iso + ird using ManaGunZ on Super Slim PS3, since it requires lvl1 and lvl2 access :(

**Comment by Zarh** [comment]
To decrypt the dump, you absolutely need a decryption key called data1, D1 or disc key. This key must be inside the ISO (I forgot the offset) to allow 3k3y ISO tools to build an IRD. It may have more extra information (like pic and d2 perhaps)...

You can find more information here : https://www.infinitydream.com/downloads/PS3/3k3y_iso_tools_user_manual_v1.0.pdf

I'm going to close this issue as it's already working (on CFW)

**Comment by kiganazil** [comment]
Thank you for your information and fast responsive. I guess I will get a old phat ps3 to cfw it and use the ManaGunZ to properly rip then. Thank you for your work!
