### ISSUE TITLE
Memory card not detected

### ISSUE THREAD

**Issue by Nadjib23** [Zarh/ManaGunZ#15]
Hello,
I created aPS2  memory card and assigned it to a slot, but when i run ManaGunZ and start the game, it don't detect the memory card.
When i quit the game and went to see the ps2 memory card, i noticed that it's not assigned to the slot, is this a commun issue ? can somebody help me with that?.

**Comment by amandamana** [comment]
this is not an issue at least on my fat PS3 running the latest Rebug
