### ISSUE TITLE
.pnach not properly translated to .CONFIG (wrong endianness in replacement opcode)

### ISSUE THREAD

**Issue by amandamana** [Zarh/ManaGunZ#18]
I successfully applied a MGZ internal .pnach to a PS2 ISO (valid md5, SLUS_200.35, CRC 773A8DAB) using 'enable widescreen' and it worked great!

However, after restoring this PS2 ISO to original (md5 validated), I wasn't able to replicate the same success by applying the widescreen .pnach to a  PS2 CONFIG. The game loaded to its main menu, but would crash when starting a new or loading a saved game.

I couldn't tell if the patch was working because the menu screen looks identical with and without the patch. I replicated this crash by making a CONFIG using the widescreen .pnach stored on /dev_usbXXX/ The two generated CONFIGs were identical.

I don't understand the 0x0A command well enough to see what the problem is, but since the same .pnach works great when applied directly the ISO, I don't think MGZ is properly translating the .pnach to a PS2 CONFIG entry.

[sample.zip](https://github.com/Zarh/ManaGunZ/files/2857029/sample.zip)

(Tested on v1.34)

**Comment by amandamana** [comment]
[sample.zip](https://github.com/Zarh/ManaGunZ/files/2856899/sample.zip)

**Comment by amandamana** [comment]
Here is the PNACH Converter 2.01 hex pattern that corresponds to the sample.zip in my previous comment:
`//patch=1,EE,00320fd0,word,3f1f49f4
//patch=1,EE,00320fcc,word,3fe3d70a
00803b45713daa3ff0eeee3e
00803b450ad7e33ff4491f3f

//patch=1,EE,0032102c,word,3f1f49f4
08000049f0eeee3e
08000049f4491f3f

//patch=1,EE,00322950,word,3f1f49f4
cdcc4c3ef0eeee3e
cdcc4c3ef4491f3f

//patch=1,EE,00320efc,word,3f1f49f4
3c3cbc3ff0eeee3e
3c3cbc3ff4491f3f

//patch=1,EE,00320f44,word,3f1f49f4
cdcccc3df0eeee3e
cdcccc3df4491f3f

//patch=1,EE,0014ca8c,word,3c014440
608597c78044013c
608597c74044013c

//patch=1,EE,00152998,word,3c014440
06a300468044013c
06a300464044013c

//patch=1,EE,00200bf8,word,3c014440
2d2000008044013c
2d2000004044013c

//patch=1,EE,0013d048,word,3c014440
2d2000028044013c
2d2000024044013c

//patch=1,EE,00144f60,word,3c014440
d48499c78044013c
d48499c74044013c

//patch=1,EE,00320fa8,word,3fe3d70a
36fa0e3c713daa3f
36fa0e3c0ad7e33f`

I'm still learning about this stuff, but it looks like MGZ might be using inconsistent endian-ness between the original opcode and the replacement opcode in the CONFIG command. Not sure which is wrong yet, probably the original.

**Comment by amandamana** [comment]
Manually converting the endianness of the replacement opcodes in the MGZ-generated PS2 CONFIG using my hex editor fixes this issue!

**Comment by Zarh** [comment]
I just noticied I didn't respond to your messages. Sorry about that, I read it on my phone then i wanted to answer on my computer but I forgot.

Thank you for your feedback, it will help me a lot, it will be fixed in the 1.36 for sure.

**Comment by amandamana** [comment]
Great! I can't wait :)

**Comment by amandamana** [comment]
confirmed fixed
