### ISSUE TITLE
My PS3 Freezes when i mount a PS2 ISO with ManaGunZ v1.34

### ISSUE THREAD

**Issue by Ali889** [Zarh/ManaGunZ#19]
Greetings Sir.

Recently, i just update my CFW Slim PS3 to STARBUGED 4.84 and using your latest version of ManaGunZ which is V1.34. Everytime runs smoothly there but as soon as i clicked to mount a PS2 ISO, my whole system is just hard freezes and power button didn't worked too. So i have to unplug the power that makes my system a little faulty. I Re-installed STARBUGED 4.84 CFW & Rebuilt Database & Restore System files to solve the issue. Now my System is OK But please Release an Update for ManaGunZ with 4.84 Support so we can Enjoy using this awesome homebrew.

**Comment by littlebalup** [comment]
Managunz 1.34 doesn't support 4.84 fw yet

**Comment by Zarh** [comment]
I close it because the version 1.35 support the fw 4.84.
