### ISSUE TITLE
Crash when are writing/reading Games configuration with no-latin/no-english alphabet (For example Shift-JIS)

### ISSUE THREAD

**Issue by sifiro** [Zarh/ManaGunZ#22]
Hi, There are some issues related with FileSystem which don't allow files with japanese characters (or is rejected by FTP Server, so... maybe both don't manage Japanese characters write/read in filesystem), 
so when ManaGunZ is writing some configuration files related with some games which have no-latin/english alphabet, crash the application.
Possible Solution: Use Game-Id for save configurations
so... maybe you need a list_game_id or create an Array of a new struct type which include game_title, Game_ID, Game_platform and Game_Path fields replacing current list_game_platform, list_game_title and list_game_path
See ya.

**Comment by Zarh** [comment]
Hi, 

I fixed the issue with UTF8 for the next update, it won't crash the app anymore. But for another purpose I had to create the array list_game_ID like yours. I decided to include your idea to use the game-Id instead of the title.

Thank you.
