### ISSUE TITLE
Disable widescreen issue not available is back with newest revision

### ISSUE THREAD

**Issue by HXNGUY01** [Zarh/ManaGunZ#27]
It's back

**Comment by Zarh** [comment]
Hi, 
I just tested it again and it look likes it's it's working. But I thought a lot about this and I may have an explanation for your issue. 

- First of all you enabled the widesreen with managunz 1.36. It patch the ISO and it created a 'backup file' in Managunz folders, to get or restore the orignal values.
- Then you uninstalled managunz 1.36, by doing this you removed the backup files too.
- Finally, you installed managunz 1.37. So, without the original value from backup files, managunz can't calculate the original CRC. Without it, the widescreen option isn't available.

If I'm right, I apologies for the trouble... I'll try to find a way to avoid this kind of issue, anyway.

If i'm wrong can tell me which backup did you use ?

Thanks.

**Comment by HXNGUY01** [comment]
I think your explaination is perfect and it's pretty much what I did.  The backups I used were Wild Arms Alter Code F and Tales of Legendia. 
Would the bandage solution be to remove the backup and put a new one in? 

Thanks

**Comment by Zarh** [comment]
Unfortunately, I think it's the only solution.

Once it's done, I advise you to go in "configuration" option and to check the box "Widescreen", if you want to use these patch without changing any value of the ISO. It will use CONFIG files, the patches will be applied to the ELF loaded in the memory.

**Comment by HXNGUY01** [comment]
Thank you very much for your help! One final question do you know if widescreen patches are available for all game or some games do not have the option for ws? Thanks

**Comment by Zarh** [comment]
Still missing some games. I'm not doing them, I found it here : https://github.com/PCSX2/pcsx2/blob/master/bin/cheats_ws.zip

And they are made by the pcsx2 community : 
https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches

**Comment by HXNGUY01** [comment]
Thanks for the response like always. Some games like tales of legendia or tekken 4 or 5 would always fail when trying to apply for widescreen patch (either flat out fail with an error or the rocket thing keeps running forever). Do you know the reasons for this?

Also I think if you get the widescreen patches from here they are more recently updated than the github link.

https://forums.pcsx2.net/Thread-PCSX2-Widescreen-Game-Patches?pid=271674#pid271674

**Comment by Zarh** [comment]
This is the link i wanted to share but I trimmed the end without noticing it.

**Comment by Zarh** [comment]
I just tested to apply the widescreen on 'tales of legendia (US)' and it's working. I think this commit : https://github.com/Zarh/ManaGunZ/commit/90d115745b60baeb91940cccb7eb0861adfb2c1e fixed your issue.

Wait for the release of 1.38 please.
