### ISSUE TITLE
Xenosaga Episode I SLUS_204.69.CONFIG file

### ISSUE THREAD

**Issue by whitezombie2000** [Zarh/ManaGunZ#28]
The SLUS_204.69.CONFIG file didn't work for me posted here. I got a black screen when loading the game with the config file posted here. I used the config file posted here https://www.psx-place.com/threads/how-to-use-config-files-on-ps2-games.17101/ and the game loaded successfully and allowed the Fix "erde kaiser" quest. The values for the configs are different in a hex editor.

PSX-Place config file.
3D 00 00 00 57 44 00 00 0F 00 00 00 00 24 32 00 00 29 32 00 00 00 00 00

Github config file
3D 00 00 00 57 44 00 00 0F 00 00 00 00 24 32 00 00 00 00 10 00 29 32 00 00 00 00 00

The ps3devwiki https://www.psdevwiki.com/ps3/PS2_Emulation#Config_file_examples_.28for_netemu.29
has this posted. So I'm not sure if the wiki is correct.

00000000  3D 00 00 00 57 44 00 00 0F 00 00 00 00 24 32 00  =...WD.......$2.
00000010  00 29 32 00 00 00 00 00                          .)2.....                          ........

**Comment by whitezombie2000** [comment]
I see the issue. The offset 00000010 was accidentally put in the config file uploaded here.

**Comment by Zarh** [comment]
Thank you very much !

**Comment by whitezombie2000** [comment]
Hello! I'm not sure why but the old SLUS_204.69.CONFIG file was uploaded that was not working. Just letting you know so you can correct it.

https://github.com/Zarh/ManaGunZ/commits/master/pkgfiles/USRDIR/sys/CONFIG/CUSTOM/SLUS_204.69.CONFIG
