### ISSUE TITLE
fatal error: openssl/opensslconf.h: No such file or directory

### ISSUE THREAD

**Issue by lmirel** [Zarh/ManaGunZ#30]
this could be a stupid thing I'm missing but I'm unable to 'make pkg' successfully due to this.
I've looked at the Makefile but I can't figure out how to configure the lib.
I guess I'll have the same issue with the other ones.
thanks in advance for any hints

**Comment by Zarh** [comment]
Indeed, it's not present because it's autogenerated header when it built the lib and gitignore remove this file when I uploaded this file...
Anyway, rebuild the lib and you'll have it.
To build it type :
cd MGZ/lib
configure_openssl
cd openssl
make
cd ..
mv openssl/libcrypto.a libcrypto.a

**Comment by lmirel** [comment]
thanks. I might be doing something work or not using the right tools for this project as I get:
f:\PSDK3v2\MinGW\msys\1.0\bin\sh.exe configure_OpenSSL
Perl v5.10.0 required--this is only v5.8.8, stopped at ./Configure line 12.
BEGIN failed--compilation aborted at ./Configure line 12.

I use the SDK from https://github.com/Joonie86/PSDK3v2 and I already adapted the paths to point to drive F

thanks in advance

**Comment by Zarh** [comment]
You just need to update perl. Don't worry, I just made a commit to include the missing headers to the project.

thanks for the feedback ;)
