### ISSUE TITLE
Freeze when mount iso from portable hdd

### ISSUE THREAD

**Issue by Bahtiar85** [Zarh/ManaGunZ#33]
After update to 4.86 HFW ps3 freeze when i mount iso

**Comment by Klairm** [comment]
It also freezes if you try to edit game settings, it happens to me

**Comment by mlody95pl** [comment]
Same on CFW Rebug 4.86.1 LITE. I use NTFS drive with ISO's in PS3ISO folder and JB games. Only power off helps.

**Comment by J013k** [comment]
I also have a problem with mounting PS2 ISOs from "hdd0:/PS2ISO".
When I'll mount it with ManaGunZ,
PS3 will freeze and power off button will not help to shut it down.
I need to takeout power cable to power it off.

Currently tested version v1.37 and v1.35.

I'm on Rebug 4.86.1 LITE CEX with Cobra 8.2 - CECH-2004A.

**Comment by Zarh** [comment]
please try this version https://github.com/Zarh/ManaGunZ/releases/tag/1.38 and tell me if it's fixed.

It support 4.86.

**Comment by J013k** [comment]
It works for me.
I manage to mount a PS2 ISO and play it for some time.
Thanks!
