### ISSUE TITLE
Se congela la aplicación y el botón de power deja de responder

### ISSUE THREAD

**Issue by MauroArgentino** [Zarh/ManaGunZ#35]
Hace poco le reemplacé el disco rígido mecánico por uno SSD de Western Digital.
Cuando quiero ver las opciones de los juegos que se encuentran en una partición NTFS y FAT32 de un disco rígido externo.. la consola se congela, y deja de responder.
La versión de firmware de la consola es 4.86 HFW.. y el modelo de consola es un CECH-300X.
En mi otra consola modelo CECH-2511 con firmware 4.84 HFW.. funciona perfecto.. y tiene un disco mecánico.

**Comment by Zarh** [comment]
please try this version https://github.com/Zarh/ManaGunZ/releases/tag/1.38 and tell me if it's fixed.

It support 4.86.

**Comment by MauroArgentino** [comment]
Hola Zarh! Joya! Mil Gracias! :D Siii.. ahí lo probé y funciona :D Ahora estoy copiando un juego al disco interno.
Todavía no la probé a la aplicación en la consola que tiene el disco SSD.. pero pienso que debería funcionar.. ya que en esta, que hace poco le instalé el firmware 4.86 HFW también hacía lo mismo de colgarse.
Por cierto.. será que podría sumarte a este proyecto? https://github.com/emukidid/wii64-ps3 Tengo mucha hype de que progrese ^.^
Un saludo! Y Muchísimas Gracias nuevamente! :D
