### ISSUE TITLE
Add Back button in file manager

### ISSUE THREAD

**Issue by Ungoose** [Zarh/ManaGunZ#36]
Is it possible to add a Back button that would allow going to a previous directory? The file manager has a very convenient button-only control scheme but going up one level requires aiming with a cursor. L1 seems to be unassigned and would probably fit this purpose.
Thanks!

**Comment by Zarh** [comment]
The current control are the following ones:

- circle : back/close
- triangle : options
- square : select
- cross :  click/open/action
- R : move window
- R3 : change the root display (maybe everywhere later)
- R2 : manage speed of L, R & Dpad (cursor/scroll/window)
- R1 + Dpad Left : Dock the window to the left
- R1 + Dpad right : Dock window to the right
- R1 + Dpad top : Dock window to full screen
- R1 + Dpad bot : undock window (default size)
- L : move cursor
- L3 : refresh window
- hold L2 : unused
- hold L1 + left : goto parent directory
- hold L1 + right : goto previous path
- L2 + R2 : screenshot (it can be used everywhere)
- start : open new window
- select : open settings (FileManager standalone)
- Dpad up : scroll up
- Dpad down : scroll down
- Dpad left : page up
- Dpad right : page down


So, to answer to your question you can use L1+Dpad left and right. I know this is not exactly what you want...

**Comment by Ungoose** [comment]
Actually, this is exactly what I was after, thank you. I'd say L1+left for previous path and L1+up for parent directory would be a more intuitive layout, though. 
In any case, thank you for your efforts.

**Comment by Zarh** [comment]
I'll add later in settings a way to customize buttons ;)
