### ISSUE TITLE
IRD verification doesn't work correctly.

### ISSUE THREAD

**Issue by dimen363** [Zarh/ManaGunZ#39]
Some PS3 ISO titles fail IRD verification despite passing it in PS3-ISO-Rebuilder (example: BLES00200 - Unreal Tournament 3). The ISO was prior rebuilt using Plain header option in PS3-ISO-Rebuilder. Currently on Rebug Lite 4.86.1.

**Comment by Zarh** [comment]
Thank you for the feedback. I'll take a look.

**Comment by Zarh** [comment]
Can you try again with the latest version ?

**Comment by Zarh** [comment]
I just tested it with MGZ 1.41 (pre-release) same backup built with ps3-iso-rebuilder.iso, the iso is splitted in 4 part inside FAT32 external device and it's worked. So, i'm closing this issue.
