### ISSUE TITLE
Filenames containing . (dot) before extension get truncated in list

### ISSUE THREAD

**Issue by zefie** [Zarh/ManaGunZ#4]
**MGZ Version:**
v1.29

**PS3 Info**:
CECHA01 REBUG 4.81.2 REX/CEX mode

**Step to Reproduce:**
Place an ISO in /dev_hdd0/PS2ISO (perhaps others) with a . in the filename before the extension, such as "SLPS25527-[.hack Fragment].iso"

**Expected result:**
To list the file in the browser.

**Actual result:**
Filename in browser gets truncated to the text before the first dot.
Example: "SLPS25527-[.hack Fragment].iso" shows as "SLPS25527-["

**Additional Examples:**
"SLUS20469-[Xenosaga Ep.1].iso" = "SLUS20469-[Xenosaga Ep"
"SLUS20562-[.hack IMOQ Part 2 (Mutation)].iso" = "SLUS20562-["

**Additional Notes:**
I have not tweaked any settings yet, this happened on the initial page shown after simply installing and executing the software, on a machine that has not used it before.

**Comment by Zarh** [comment]
thanks for the feedback, i'll fix it it the next update.
