### ISSUE TITLE
Doing anything inside Managunz freezes the system on 4.87 Hen 3.0.2. On 4.86 with Hen 3.0.2, didn't freeze.

### ISSUE THREAD

**Issue by Adamanimus** [Zarh/ManaGunZ#42]
Trying to mount backup, pressing triangle to select game options etc... freezes the system. It is a new HDD with clean install.

**Comment by MauroArgentino** [comment]
El problema es que esta versión, la 1.38 no está firmada con las nuevas keys para el firmware 4.87.
Habrá que esperar que Zarh lo vuelva a compilar con las nuevas keys.
Me pasaba lo mismo con la versión 1.37.. cuando yo estaba en el firmware 4.85.

**Comment by Adamanimus** [comment]
1.39 released adding support for new firmware.
