### ISSUE TITLE
Jb Game menu(triangle) freezes ps3

### ISSUE THREAD

**Issue by retrosapien** [Zarh/ManaGunZ#47]
I'm using hen hfw 4.87

Everytime I press triangle on a JB game to open game menu, the ps3 freezes and I have to long press the power button. 
(I noticed webman mod's web server is disabled, too. I usually use that to power off when the ps3 soft locks. )

It works ok on a ps1 game. Can't confirm for ps3 iso's or ps2 classics as they don't seem to be listed. 

I really only installed this to use the check files(ird) function. When ftping a JB game I noticed some files timed out, but didn't note which ones. I was hoping your ird check could help identify which ones are incomplete. 

Could this function be added to the stand alone file manager pkg? Or maybe it already is but hidden? 

Is there another homebrew out there that just does ird check? 

I've made a md5 text file with md5sum of all the files in the JB game folder. Is there a way I could use that on the ps3 to check the game files somehow?

Thanks in advance for your help. 

(One more thing I thought about, I don't have multiman installed, but that shouldn't be a problem, right? I just remembered reading some apps need it, or at least the folder to exist)

**Comment by Zarh** [comment]
It's probably becaude you were on 4.87, which wasn't completly supported yet.  Try with the latest version.
