### ISSUE TITLE
Pressure Sesitive Buttons for PS2 games

### ISSUE THREAD

**Issue by bananabeanboozle** [Zarh/ManaGunZ#53]
Is there anyway to implement the pressure sensitive face and shoulder buttons while playing ps2 games? Currently games that use them such as the GTA games and GT4 dont function correctly when accelerating the vehicles because of this. To me this is the one feature missing that would make emulating ps2 games on the ps3 almost perfect.

**Comment by Zarh** [comment]
@mrjaredbeta discovered that the cmd 0x50 is used to enable pressure sensitivity : https://www.psx-place.com/threads/compatibility-list-ps2-on-ps3.1306/page-240#post-308231

you can try to enable it on 'configuration' in managunz or directly use the CONFIG from here : https://www.psx-place.com/threads/compatibility-list-ps2-on-ps3.1306/page-240#post-308241

I added the description of this cmd in managunz for the next update, I'm closing this issue :p
