### ISSUE TITLE
[DUMP] Error when try to dump a disc when there is not a properly folder

### ISSUE THREAD

**Issue by jhonathanc** [Zarh/ManaGunZ#54]
I tried to dump a PS3 disc, but as there is no PS3ISO folder, the dump process fails.

I created the PS3ISO folder manually and it worked.

**Comment by Zarh** [comment]
Thank you, it's fixed by https://github.com/Zarh/ManaGunZ/commit/2b0289484d13953b5cd1ffbb62a93f1f85e4188f
