### ISSUE TITLE
Dumping decrypted disc and Blu-Ray key to NTFS often causes system to freeze.

### ISSUE THREAD

**Issue by foliage-burner** [Zarh/ManaGunZ#55]
I'm not sure if the problem is unique to NTFS, as I haven't tried dumping to internal with ManaGunZ. Nevertheless, the freezes occur moderately often, and require one to forcefully shut off the PS3 to fix.

Edit 1: Ok, some more information. With both options (dumping disc and key), the system freezes when there doesn't exist a PS3ISO folder in the target directory. Furthermore, dumping the bluray key freezes the system when writing to NTFS.

Edit 2: Dumping the disc key to NTFS now reports "failed to fopen (target disc write path)". I think the freezes occur only if you try to dump the disc key after dumping the disc, but I could be wrong.

Edit 3: Forgot to mention: During these freezes, the progress screen is never loaded, so the problem must occur during or before loading, I would guess.

Edit 4: Looking at the code of Irisman, it calls ps3ntfs_mkdir(tmp_path, 0777) before running makeps3iso. Perhaps this could fix this issue, but I'm not sure about the disc key error when dumping to NTFS. The call is made in line 7343 in main.c of Irisman.

Edit 5: Decided to merge my comments.

Edit 6: Considering how small the bluray key is, perhaps it would be better to simply remove the option to dump it to ntfs, and require one to use a fat-32 flash drive. Though, if you can fix the freezing issue, it is always nice to have additional options available.

**Comment by foliage-burner** [comment]
Ok, some more information. With both option (dumping disc and key), the system freezes when there doesn't exist a PS3ISO folder in the target directory. Furthermore, dumping the bluray key freezes the system when writing to NTFS.

**Comment by foliage-burner** [comment]
Dumping the disc key to NTFS now reports "failed to fopen (target disc write path)". I think the freezes come only if you try to dump the disc key after dumping the disc, but I could be wrong.

**Comment by foliage-burner** [comment]
Forgot to mention: During these freezes, the progress screen is never loaded, so the problem must occur during or before loading, I would guess.

**Comment by foliage-burner** [comment]
Looking at the code of Irisman, it calls ps3ntfs_mkdir(tmp_path, 0777) before running makeps3iso. Perhaps this could fix this issue, but I'm not sure about the disc key error when dumping to NTFS.

**Comment by Zarh** [comment]
Were you using ManaGunZ v1.40 ?

**Comment by foliage-burner** [comment]
Yes, I'm using v1.40. I will recheck dumping decrypted ISOs without a folder again, though, because it seems it was fixed in this release, and I may have tested this on v 1.39 accidentally. Dumping the Blur-Ray key was definitely tested on v1.40 though.

**Comment by foliage-burner** [comment]
Ok, dumping an encrypted and decrypted Blu-Ray w/o a preexisting PS3ISO folder is giving me an fopen error. No freeze though, so I must have tested dumping the decrypted ISO on v1.39. I will try to check if the error is caused by anything else.

**Comment by foliage-burner** [comment]
Few more tests: When the PS3ISO folder is present, dumping decrypted and encrypted ISOs works like a charm. Dumping the Blu-Ray disc key still gives an fopen error though.

**Comment by Zarh** [comment]
I found the cause of this issue ! It will be fixed for the next update :)

**Comment by foliage-burner** [comment]
Tested latest test build for 1.41, and the issue is gone. Thanks! Closing issue now.
