### ISSUE TITLE
Integrating the GetKeys package from Redump into ManaGunZ?

### ISSUE THREAD

**Issue by ghost** [Zarh/ManaGunZ#57]
With your latest changes to ManaGunZ, it is much easier to do a lot of the things that Redump requires for submissions, especially with 3Dump.bin generation. Though, now that that is available, it might be worth integrating the GetKeys package that Redump uses into ManaGunZ. I don't know if the Blu-Ray keys that ManaGunZ generates have any correlation with the dkeys that Redump uses? Maybe they can be used for the same thing?

GetKeys package+source: https://archive.org/download/GetKeyR2GameOS.7z/GetKey-r2-GameOS.7z

Sorry for so many issues, I just thought this would be the next logical step after adding the ability to generate 3Dump.bin

**Comment by Zarh** [comment]
I already dump these key inside disc.key and the ird.

redump store these keys inside a txt file, I'm not even sure if they use them I don't have access to the hidden section of redump.org... do they ? I heard they dumped a lot of disc.  So, what I'm suppose to do is to store these key inside a txt file  ?

Something is bothering me : 
PIC is supposed to be 0x70 (see below) but 3key team used a length of 0x73 for ird, and redump 0x84... https://www.t10.org/ftp/t10/document.04/04-328r0.pdf#page=43

**Comment by foliage-burner** [comment]
They do use ask for the keys when dumping a game: http://wiki.redump.org/index.php?title=PlayStation_3_Dumping_Guide. Here is an example of a submission (public because it is recent): http://forum.redump.org/topic/37185/ps3-star-ocean-the-last-hope-international/

They normally ask for the log generated by the GetKeys package for legitimacy (so that it is not a repost of information which somehow leaked), so for Redump you'd probably also want to generate that text file. Of course, that would just be implementing features for Redump compatibility, so I'm not sure you'd still be interested in adding something like that to ManaGunZ.

There may be something weird going on with the PIC, maybe for PS3 Sony implemented a different length. Not too familiar with the ISO/Blu-Ray format, so I'll try to do some research on it.

**Comment by Zarh** [comment]
It doesn't bother me at all. I like redump.org, I'll add the exact same function if you want, it doesn't really matter. I was just curious :)

**Comment by InternalLoss** [comment]
```
Common Disc Info:
    Title: Star Ocean: The Last Hope International
    Foreign Title (Non-latin): スターオーシャン４－ＴＨＥＬＡＳＴＨＯＰＥ－ＩＮＴＥＲＮＡＴＩＯＮＡＬ
    System: Sony PlayStation 3
    Media Type: BD-ROM-25
    Category: Games
    Region: Japan
    Languages: Japanese
    Disc Serial: BLJM 60338

    Ringcode Information:
        Data Side Mastering Codelaser branded/etched): BLJM-60189   2
        Data Side Mastering SID Code: IFPI L280
        Data Side Toolstamp or Mastering Codeengraved/stamped):04
        Data Side Mould SID Code:
        Data Side Additional Mould:
        Label Side Mould SID Code: 453H
    Barcode: 4  988601  006958
    Comments:
    Contents:

Version and Editions:
    Version: 1.01
    Edition/Release: Ultimate Hits

Extras:
    Primary Volume DescriptorPVD):

0320 : 20 20 20 20 20 20 20 20  20 20 20 20 20 32 30 30                200
0330 : 39 31 30 32 36 30 32 31  35 30 30 30 30 00 30 30   9102602150000.00
0340 : 30 30 30 30 30 30 30 30  30 30 30 30 30 30 00 30   00000000000000.0
0350 : 30 30 30 30 30 30 30 30  30 30 30 30 30 30 30 00   000000000000000.
0360 : 30 30 30 30 30 30 30 30  30 30 30 30 30 30 30 30   0000000000000000
0370 : 00 01 00 00 00 00 00 00  00 00 00 00 00 00 00 00   ................

Disc Key = 4f60e763ed870444a07de963dbe23e8b
Disc ID = 00000000000000ff00020001XXXXXXXX
    Permanent Information & ControlPIC):

10020000444901080000200042444F01
110101000000000000C3F8BF00100000
00C3F8BE000000000000000000000000
00000000000000000000000000000000
Size & Checksum:

    Size: 17635016704
    CRC32: 0c6a5d01
    MD5: 50a6e4d88b834cb181f8a414af04514b
    SHA1: 3386156367811031df4d52fdd874f1f44818d45e
```

This is the data in that Redump post that was hidden - dumpers can still see "History for Dumps"

This does sound like a cool new way to dump, and I'm sure people will test this new method out c:
