### ISSUE TITLE
Create ICON0

### ISSUE THREAD

**Issue by Zarh** [Zarh/ManaGunZ#70]
> When I first installed Managunz I had no idea covers had to be transferred to its covers folder, and not game ISO folder for "create ICON0" option to work. I put cover alongside the ISO and kept pressing on that option thinking it was broken when nothing happened. Specifying that in the help section would be nice.

from : https://github.com/Zarh/ManaGunZ/issues/68#issuecomment-921881823

**Comment by Zarh** [comment]
Now, the icon0 will be saved at "BackupPath.ICON0.jpg"

**Comment by Derp0** [comment]
Perfect!
That's exactly how I thought they were supposed to be created initially.
