### ISSUE TITLE
Managunz not showing the background image (PIC1) after using the image viewer

### ISSUE THREAD

**Issue by Derp0** [Zarh/ManaGunZ#72]
Found a bug when testing for #61.

Going to the file explorer, opening an image and exiting immediately causes Managunz not to show the background image (PIC1). You'd have to navigate to the other game types and back to load it.

Here's a screenshot:

https://i.imgur.com/7BRp3h2.png

**Comment by Zarh** [comment]
fixed with https://github.com/Zarh/ManaGunZ/commit/2fa3e2cead640e7c16069ce226de4a7e98f399ab
