### ISSUE TITLE
Possible bug/issue when extracting pkgs

### ISSUE THREAD

**Issue by rhynec** [Zarh/ManaGunZ#78]
While looking at the different tools available to unpack retail pkgs, I came across [this article](https://hackinformer.com/2015/10/05/adapted-package-tool-kakaroto/) about a fork of Kakaroto's pkgtool by Zecoxao and ZeroTolerance. According to the article, Zecoxao added support for pkg with "many files" and "files with size of 2gb or bigger." Unfortunately, Zecoxao's repo for the source of the tool seems to no longer exist, and I wasn't able to find the source code anywhere. So, I decided to look at the code of the original pkgtool to see exactly what caused the limitations that Zecoxao fixed.

Unfortunately, I wasn't able to find what was limiting the total number of files from being extracted, but I believe I found the "bug" which would make it impossible to properly extract pkgs with internal files bigger than 2gb:

The "bug" in question has to do with the paged_file_splice function in paged_file.c. For some reason,it only accepts signed ints as the length of what to splice, whereas pkg internal files allow for a maximum size of u64 (which pkgtool stores correctly). I'm not exactly sure why an int is used as a parametere inside the function instead of using u64.

The function is called in the pkg_unpack function, and I think that if a pkg with files of size bigger than 2gb is called, the output file should be of size (original size % 2gb), if I understand correctly how C compilers handle downcasting. I think the splice function can be safely modified to accept only u64 values, as I don't see a case when the input should be negative (in fact, I think splice is only called inside pkg_unpack and nowhere else).

Anyway, I don't own/know-of a retail pkg with files bigger than 2gb to test properly what exactly happens when extracting such a package. Maybe someone else could test extracting such a pkg?

Edit: "Downcasting" seems to be implementation independent. With PSDK3v2 using gcc, I think the int will be spliced to only the least significant digits.

**Comment by rhynec** [comment]
Ok, I found the problem with extracting pkgs with "many files". In the pkg_open function, memory is allocated for an array meant to hold multiple PKG_FILE_HEADER structs (file directories, basically). So, the size allocated is "header->item_count*sizeof(PKG_FILE_HEADER)" The problem is that item_count is an unsigned 32 bit integer, whereas malloc can only guarantee memory space of 64kb in size, per the C99 standard. Thus, considering that sizeof(PKG_FILE_HEADER) resolves to 32, the maximum number of files that can be guaranteed extracted from the pkg is 2048. If I understand the code correctly, the worse that can happen with packages of greater size is that the rest of the files from the package are just ignored. A way to fix this issue would be to instead use multiple arrays to store the file headers if they happen to "overload" the amount of space malloc guarantees.

Moreover, even if the malloc problem can be solved, paged_file_read would still need to be modified, since it only accepts unsigned 32 birt integers, whereas "header->item_count*sizeof(PKG_FILE_HEADER)" could be bigger than 2^32 when there are 2^27 flies present in the pkg, which is somewhat unlikely TBH. Fixing the malloc problem would probably solve most issues one could come across when extracting a package.

**Comment by rhynec** [comment]
I made a small patch which should fix the 2gb limit/bug for file extraction [here](https://github.com/rhynec/pkgtool/tree/size-patch). I have no way of testing it, unfortunately, so I can't be sure if it works or not. Hopefully you can test it with ManaGunZ.

A safe solution to the file number problem would be to build a 2D array to store more file directories. If disc games are anything to go by, a game will have at most 110,000 files according to Aldo's ird database (and even that is an outlier). That's approximately 2^20 files at most, and with each file directory being 32 bytes long, the maximum storage needed for directories would be 2^25, which fits into the space guaranteed by the gcc C99 standard in a square array using malloc (size (2^16)^2).

But, I guess building that 2D array could be avoided if we knew what size_t resolves to in PSL1GHT. If it's an unsigned 32 bit integer, then this patch is probably unnecessary. Otherwise, if size_t is an unsigned 16 bit integer, the patch might be beneficial as quite a handful of games will probably have more than 2048 files.

**Comment by Zarh** [comment]
I think size_t is u32.
I was able to extract a pkg with 3000+ files, I think it's more than enough.
I included pkg stuff in managunz to build PKG shortcut. (which are reaaly small pkg). Later, I added in filemanager options to build/extract pkg.
I'm aware it is not the best tool. It's really slow. I rarely use it. I'd rather using PC tools which 10 times faster ;)

I fixed the issue with big files just like you suggested (thank you btw) but I won't work the other issue (very large amount of files).

**Comment by rhynec** [comment]
> I won't work the other issue (very large amount of files), sry.

No problem! With size_t resolving to u32, the maximum amount of files that MGZ could handle should be approximately 2^27, which is about 134 million individual files. No package will have that many files, so it isn't an issue at all thankfully.
