### ISSUE TITLE
Tag/Tree for v1.41 incorrect

### ISSUE THREAD

**Issue by rhynec** [Zarh/ManaGunZ#84]
The tree tagged with v1.41 (link [here](https://github.com/Zarh/ManaGunZ/tree/1.41)) has as its latest commit dated back to June 25 of 2021, whereas the published v1.41 should be using the latest tree, after the commit adding support for unlocking hdd0 ([this](https://github.com/Zarh/ManaGunZ/tree/09e2e4112885ecbbb91bf91d5398bfff215bc4aa) one).

Also, perhaps it would be best to update the custom PS2 configs with the most current ones from wMM with this new release. Or, for better modularity, perhaps remove configs entirely from MGZ and ask people to install the separate PS2CONFIG package that Aldo provides (given how often custom configs are changed compared with MGZ's release cycle). Just an idea.

**Comment by Zarh** [comment]
Thanks, I fixed the tags (thanks to google). It was caused by the pre-release.

I'll probably remove the CONFIG files included in mgz. I think the external pkg of aldostool is the best solution.
